Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'Gmedia.SendgridFinisher:EmailFinisher':
            implementationClassName: Gmedia\SendgridFinisher\Finishers\EmailFinisher
            options:
              'format': 'html'
              'trackingSettings':
                'click_tracking':
                  'enable': false
                  'enable_text': false
                'open_tracking':
                  'enable': false
                  'substitution_tag': ''
                'subscription_tracking':
                  'enable': false
                  'text': ''
                  'html': ''
                  'substitution_tag': ''
                'ganalytics':
                  'enable': false
                  'utm_source': ''
                  'utm_medium': ''
                  'utm_term': ''
                  'utm_content': ''
                  'utm_campaign': ''

Gmedia:
  SendgridFinisher:
    apiKey: ''
    apiOptions:
      mailSettings:
        sandboxMode: false
